### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by Partixel** [vercas/vNet-for-GMod#1]
1. Are corrupted packets re-sent ?
2. Which would be faster; Table serialised with vON then sent as a string or Table sent using :Table()
3. I assume I can distribute this within a sold gmod addon as with vON, just want to make sure ?

**Comment by vercas** [comment]
vNet doesn't do anything as far as channel reliability is concerned. The
Source networking protocol that Garry uses for net library does.
I believe that a net message that didn't arrive or arrived too late (after
the 'next' message) will really mess things up.
This is unlikely to happen, though. It never happened to me while testing.

As far as tables go, the _:Table_ function is much faster and more
space-efficient than vON. It also supports more data types.
If your table is already encoded with vON (e.g. loaded from a file), I
recommending sending that, as a string. This will avoid re-encoding (and
possibly a decoding before that) and a file buffer.

And yeah, you are free to use vNet commercially as long as you give me
proper credits in the about/credits area of your addon.

**Comment by Partixel** [comment]
Okay, I have done. Thanks for the info!
