### ISSUE TITLE
Data not being removed?

### ISSUE THREAD

**Issue by Partixel** [vercas/vNet-for-GMod#2]
![image](https://cloud.githubusercontent.com/assets/2728862/7514421/00e4ff4e-f4b5-11e4-9d92-50303ac3a89a.png)

**Comment by vercas** [comment]
That can happen during crashes or when quitting.

Every time the server/client starts up, the folder is deleted completely.

**Comment by Partixel** [comment]
![image](https://cloud.githubusercontent.com/assets/2728862/7551113/e30c3f3e-f674-11e4-80b6-d0cbe632510e.png)

After typing "quit" in the console:

![image](https://cloud.githubusercontent.com/assets/2728862/7551116/0661073a-f675-11e4-924a-81a7a442295f.png)

**Comment by Partixel** [comment]
And then starting it up again, the files stay the same

**Comment by Partixel** [comment]
Think I found the problem:

"file.Delete - Deletes a file or _empty_ folder that is relative to the data folder. You can't remove any files outside of data folder."

**Comment by vercas** [comment]
Ah, you are right.  

Obviously the function won't let me know that something's wrong.
I'll get this fixed in a minute.

**Comment by Partixel** [comment]
Okay :)

**Comment by Partixel** [comment]
Something like this works:

``` lua
local function deleteFolder( Path )

    local Files, Dirs = file.Find( Path .. "/*", "DATA" )

    for a, b in ipairs( Files ) do

        file.Delete( Path .. "/" .. b )

    end

    for a, b in ipairs( Dirs ) do

        deleteFolder( Path .. "/" .. b )

    end

    file.Delete( Path )

end


if file.IsDir("vnet", "DATA") then
    deleteFolder("vnet")
end
```

**Comment by vercas** [comment]
Try the latest version, please. It should be fixed.
Also, please try manually deleting the folder before starting up. (after you check if it deletes the files inside)

**Comment by Partixel** [comment]
line 79, "Remove" is nil

should be file.Delete

**Comment by vercas** [comment]
Try now. :(
I haven't coded for GMod or played it for quite some time.

**Comment by Partixel** [comment]
Yep, works now.

And don't worry about it, I make worse mistakes all the time..
