### ISSUE TITLE
HELL o World! // examples

### ISSUE THREAD

**Issue by SupinePandora43** [vercas/vNet-for-GMod#3]
is there any examples of using it?!

**Comment by vercas** [comment]
I haven't touched GMod in over 5 years. I cannot think of anything that uses it, sorry.

**Comment by Pdzly** [comment]
ok very sad

**Comment by Pdzly** [comment]
But with that i cant even figure it out by myself because its tooo biiiiiiiiiiiiiiiiiiiiiiiig
